language: bash

branches:
  only:
    - master

sudo: required

dist: xenial

before_script:
  # Install snapd, which we need to install microk8s
  - sudo apt-get update
  - sudo apt-get install -y snapd

  # Install microk8s and set it up
  - sudo snap install microk8s --classic
  - microk8s.start
  - microk8s.status --wait-ready
  - microk8s.enable dns storage
  - microk8s.status --wait-ready

  # Install help and set it up
  - sudo snap install helm --classic
  - helm init --wait

script:
  # Debug print cluster information
  - microk8s.kubectl cluster-info

  # Install our helm chart
  - helm install --wait --set "ingress.enabled=false" .

  # Get reference to our pod
  - export POD_NAME=$(microk8s.kubectl get pods --namespace default -l "app.kubernetes.io/name=bitwarden" -o jsonpath="{.items[0].metadata.name}")

  # Port forward our pod
  - microk8s.kubectl port-forward $POD_NAME 31111:80 &

  # Test that the HTTP vault is presented
  - curl -s localhost:31111 | grep "Bitwarden Web Vault"

