apiVersion: v1
appVersion: "1.5.0"
description: A Helm chart to install bitwarden_rs
name: bitwarden
version: 0.1.1
home: https://github.com/Skeen/helm-bitwarden_rs
maintainers:
- name: Skeen
  email: sovende@gmail.com
