{{- $fullName := include "bitwarden.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bitwarden.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bitwarden.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        bitwarden-config-hash: {{ include "bitwarden.config-hash" . | sha256sum }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ $fullName }}-conf
        {{- if or (eq .Values.database.type "mysql") (eq .Values.database.type "postgresql") }}
        - secretRef:
          {{- if .Values.database.existingSecret }}
            name: {{ .Values.database.existingSecret }}
          {{- else }}
            name: {{ $fullName }}-database
          {{- end }}
        {{- end }}
        {{- if .Values.smtp.enabled }}
        - secretRef:
          {{- if .Values.smtp.existingSecret }}
            name: {{ .Values.smtp.existingSecret }}
          {{- else }}
            name: {{ $fullName }}-smtp
          {{- end }}
        {{- end }}
        {{- if .Values.deployment.secrets }}
        {{- range .Values.deployment.secrets }}
        - secretRef:
            name: {{ . }}
        {{- end }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.bitwarden.rocket_port }}
          protocol: TCP
        {{- if .Values.bitwarden.websocket_enabled }}
        - name: ws
          containerPort: {{ .Values.bitwarden.websocket_port }}
          protocol: TCP
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        {{- if .Values.securityContext.enabled }}
        securityContext:
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
        {{- end }}
        {{ if .Values.storage.enabled -}}
        volumeMounts:
        - mountPath: {{ .Values.storage.path }}
          name: data-storage
        {{ end }}
        {{- with .Values.deployment.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.smtp.enabled }}
      initContainers:
      - name: force-smtp-env
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        command:
          - sh
          - /scripts/update-config.sh
        envFrom:
        - configMapRef:
            name: {{ $fullName }}-conf
        - secretRef:
          {{- if .Values.smtp.existingSecret }}
            name: {{ .Values.smtp.existingSecret }}
          {{- else }}
            name: {{ $fullName }}-smtp
          {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: conf-scripts
        {{ if .Values.storage.enabled -}}
        - mountPath: {{ .Values.storage.path }}
          name: data-storage
        {{ end }}
        {{- with .Values.deployment.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
      - name: conf-scripts
        configMap:
          defaultMode: 493
          name: {{ $fullName }}-scripts
      {{ if .Values.storage.enabled -}}
      - name: data-storage
        persistentVolumeClaim:
         claimName: {{ $fullName }}-pv
      {{ end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
